pub(crate) mod conflict_compare_view;
pub(crate) mod conflict_list_view;
pub(crate) mod conflict_menu_bar_view;
pub(crate) mod edit_menu_bar_view;
pub(crate) mod edit_record_editor_view;
pub(crate) mod edit_records_list_view;
pub(crate) mod map_view;
pub(crate) mod modal_compare_view;
pub(crate) mod modal_settings;
